"""Dependency value-flow and state facts audited against handlers."""

from __future__ import annotations

_DEPENDENCY_TOOL_OUTPUT_FIELDS: dict[str, dict[str, tuple[str, ...]]] = {
    "banking": {
        "list_accounts": ("account_id",),
        "list_scheduled_transfers": (
            "scheduled_txn_id", "from_account", "to_account",
        ),
        "schedule_transfer": (
            "scheduled_txn_id", "from_account", "to_account",
        ),
    },
    "calendar": {
        "add_attendee": ("event_id", "attendees", "response"),
        "change_timezone": ("timezone",),
        "check_conflicts": ("event_id",),
        "create_event": ("event_id",),
        "create_recurring": ("event_id", "recurrence"),
        "delete_event": ("event_id",),
        "export_calendar": ("event_id",),
        "get_event": ("event_id",),
        "get_free_busy": ("busy", "query_range"),
        "get_recurring_info": (
            "event_id", "recurrence", "until", "count",
        ),
        "get_working_hours": ("timezone",),
        "list_events": ("event_id",),
        "remove_attendee": ("event_id", "attendees"),
        "respond_to_event": ("event_id", "email", "response"),
        "search_events": ("event_id",),
        "set_reminder": ("event_id", "reminders"),
        "update_event": ("event_id",),
    },
    "crm": {
        "list_contacts": ("contact_id",),
        "list_deals": ("contact_id", "deal_id", "lead_id"),
        "list_leads": ("contact_id", "lead_id"),
    },
    "email": {
        "list_inbox": ("email_id", "thread_id"),
        "search_emails": ("email_id", "thread_id"),
        "get_thread": ("email_id", "thread_id"),
    },
    "food_delivery": {
        "list_orders": ("order_id", "restaurant_id"),
        "list_restaurants": ("restaurant_id",),
    },
    "issue_tracker": {
        "list_issues": ("issue_id", "sprint_id"),
    },
    "payments": {
        "cancel_payment": ("invoice_id", "payment_id", "amount"),
        "create_invoice": ("invoice_id", "amount"),
        "create_webhook": ("webhook_id",),
        "get_invoice": (
            "invoice_id",
            "payment_id",
            "refund_id",
            "amount",
        ),
        "list_invoices": (
            "invoice_id",
            "payment_id",
            "refund_id",
            "amount",
        ),
        "list_webhooks": ("webhook_id",),
        "pay_invoice": ("invoice_id", "payment_id", "amount"),
        "refund_invoice": ("invoice_id", "refund_id", "amount"),
    },
    "shopping": {
        "add_review": ("product_id", "review_id"),
        "add_to_cart": ("product_id",),
        "add_to_wishlist": (),
        "apply_coupon": ("coupon",),
        "clear_cart": (),
        "checkout": ("order_id",),
        "compare_products": ("product_id",),
        "get_cart": ("product_id",),
        "get_coupons": ("code",),
        "get_order": ("order_id", "product_id"),
        "get_product": ("product_id",),
        "get_recommendations": ("product_id",),
        "get_return_status": ("return_id", "order_id", "product_id"),
        "get_reviews": ("product_id", "review_id"),
        "get_wishlist": ("product_id",),
        "list_categories": (),
        "list_orders": ("order_id",),
        "remove_from_cart": ("product_id",),
        "remove_from_wishlist": (),
        "return_order": ("order_id", "return_id", "product_id"),
        "search_products": ("product_id",),
        "cancel_order": ("order_id",),
        "update_cart_quantity": ("product_id",),
    },
    "team_chat": {
        "list_channels": ("channel_id",),
    },
}

# Conservative typed output/reference contracts used only to detect a direct
# contradiction in an LLM-classified explicit edge.  These include foreign-key
# IDs returned by the source, not just the entity it creates.  Missing entries
# fall back to _CREATED_ENTITY_BY_TOOL and therefore never invent output facts.
_DOMAIN_TOOL_OUTPUT_ENTITY_TYPES: dict[str, dict[str, set[str]]] = {
    "email": {
        "create_draft": {"draft"},
        "create_filter": {"filter"},
    },
    "issue_tracker": {
        "create_subtask": {"subtask", "issue", "user"},
    },
    "shopping": {
        "checkout": {"order"},
        "get_cart": {"cart_item", "product"},
        "get_order": {"order", "product"},
        "get_recommendations": {"product"},
        "get_return_status": {"return", "order", "product"},
        "get_wishlist": {"product"},
        "list_orders": {"order"},
        "return_order": {"return", "order", "product"},
        "search_products": {"product"},
    },
    "team_chat": {
        "create_thread": {"thread", "channel", "message"},
    },
}


# Identifier-level compatibility only.  This does not establish target state.
# In shopping, ``cart_item`` is a catalog product identified by the same
# product_id plus a live cart-membership precondition, which Step 2 checks
# separately using value intersections.
_DEPENDENCY_ENTITY_TYPE_COMPATIBILITY: dict[
    str, dict[str, set[str]]
] = {
    "shopping": {
        "product": {"cart_item"},
        "cart_item": {"product"},
    },
}


# Human-audited handler facts where a syntactic output/required-input binding
# can never satisfy the target's fixed state precondition. These facts certify
# cache classifications only; live execution and replay remain authoritative.
_DEPENDENCY_FIXED_PRECONDITION_CONTRADICTIONS: dict[
    str, dict[tuple[str, str], str]
] = {
    "calendar": {
        (
            "create_event", "get_recurring_info",
        ): "create_event always creates a non-recurring event, while get_recurring_info requires recurrence metadata",
    },
    "shopping": {
        (
            "checkout", "return_order",
        ): "checkout creates a placed order, while return_order accepts only shipped orders",
        (
            "checkout", "remove_from_cart",
        ): "checkout clears the cart before remove_from_cart can consume that membership",
        (
            "checkout", "update_cart_quantity",
        ): "checkout clears the cart before update_cart_quantity can consume that membership",
        (
            "get_return_status", "return_order",
        ): "a discovered return belongs to an order already in the return lifecycle, while return_order accepts only shipped orders",
    },
    "payments": {
        (
            "pay_invoice", "cancel_payment",
        ): "pay_invoice creates a settled payment, while cancel_payment accepts only pending payments",
    },
}


# Structured state facts used by the local relation audit.  Every tool in a
# covered domain must be present, including tools with no relevant predicate;
# presence means the handler was reviewed, while absence means insufficient
# evidence.  Predicates carrying ``:product_id`` refer to the same concrete
# product identity on both sides of an implicit edge.
_DEPENDENCY_TOOL_STATE_PRECONDITIONS: dict[
    str, dict[str, frozenset[str]]
] = {
    "calendar": {
        "list_events": frozenset(),
        "search_events": frozenset(),
        "get_event": frozenset({"event_exists:event_id"}),
        "create_event": frozenset(),
        "update_event": frozenset({"event_exists:event_id"}),
        "delete_event": frozenset({"event_exists:event_id"}),
        "create_recurring": frozenset(),
        "add_attendee": frozenset({"event_exists:event_id"}),
        "remove_attendee": frozenset({
            "event_exists:event_id", "attendee_member:email",
        }),
        "get_free_busy": frozenset(),
        "check_conflicts": frozenset(),
        "set_reminder": frozenset({"event_exists:event_id"}),
        "get_working_hours": frozenset(),
        "change_timezone": frozenset(),
        "respond_to_event": frozenset({
            "event_exists:event_id", "attendee_member:email",
        }),
        "export_calendar": frozenset(),
        "get_recurring_info": frozenset({
            "event_exists:event_id", "event_recurring:event_id",
        }),
    },
    "shopping": {
        "search_products": frozenset(),
        "get_product": frozenset({"product_exists:product_id"}),
        "list_categories": frozenset(),
        "compare_products": frozenset({"products_exist:product_ids"}),
        "get_recommendations": frozenset(),
        "add_to_cart": frozenset({
            "product_exists:product_id", "stock_sufficient:product_id",
        }),
        "update_cart_quantity": frozenset({
            "cart_member:product_id",
        }),
        "remove_from_cart": frozenset({"cart_member:product_id"}),
        "get_cart": frozenset(),
        "clear_cart": frozenset(),
        "apply_coupon": frozenset(),
        "get_coupons": frozenset(),
        "checkout": frozenset({"cart_nonempty"}),
        "get_order": frozenset({"order_exists:order_id"}),
        "list_orders": frozenset(),
        "cancel_order": frozenset({"order_exists:order_id"}),
        "return_order": frozenset({
            "order_exists:order_id", "order_status:shipped",
        }),
        "get_return_status": frozenset({"return_exists:return_id"}),
        "add_review": frozenset({
            "product_exists:product_id",
            "review_eligible:product_id",
            "review_not_already_authored:product_id",
        }),
        "get_reviews": frozenset({"product_exists:product_id"}),
        "add_to_wishlist": frozenset({"product_exists:product_id"}),
        "remove_from_wishlist": frozenset({"product_exists:product_id"}),
        "get_wishlist": frozenset(),
    },
    "banking": {
        "list_accounts": frozenset(),
        "get_account_info": frozenset({"account_exists:account_id"}),
        "get_balance": frozenset({"account_exists:account_id"}),
        "get_history": frozenset({"account_exists:account_id"}),
        "get_statement": frozenset({"account_exists:account_id"}),
        "transfer": frozenset({"account_exists:from_account", "account_exists:to_account", "account_not_frozen:from_account"}),
        "wire_transfer": frozenset({"account_exists:from_account", "account_not_frozen:from_account"}),
        "deposit": frozenset({"account_exists:account_id"}),
        "withdraw": frozenset({"account_exists:account_id", "account_not_frozen:account_id"}),
        "bill_pay": frozenset({"account_exists:account_id", "account_not_frozen:account_id"}),
        "schedule_transfer": frozenset({"account_exists:from_account", "account_exists:to_account", "account_not_frozen:from_account", "account_not_frozen:to_account"}),
        "list_scheduled_transfers": frozenset(),
        "cancel_transfer": frozenset({"scheduled_transfer_exists:scheduled_txn_id"}),
        "freeze_account": frozenset({"account_exists:account_id"}),
        "unfreeze_account": frozenset({"account_exists:account_id", "account_frozen:account_id"}),
        "verify_account": frozenset({"account_exists:account_id"}),
        "get_exchange_rate": frozenset(),
        "apply_loan": frozenset({"account_exists:account_id", "account_not_frozen:account_id"}),
    },
    "crm": {
        "create_contact": frozenset(),
        "list_contacts": frozenset(),
        "update_contact": frozenset({"contact_exists:contact_id"}),
        "delete_contact": frozenset({"contact_exists:contact_id"}),
        "list_leads": frozenset(),
        "create_lead": frozenset(),
        "update_lead": frozenset({"lead_exists:lead_id"}),
        "delete_lead": frozenset({"lead_exists:lead_id"}),
        "convert_lead": frozenset({"lead_exists:lead_id"}),
        "list_deals": frozenset(),
        "get_deal": frozenset({"deal_exists:deal_id"}),
        "create_deal": frozenset(),
        "update_deal": frozenset({"deal_exists:deal_id"}),
        "list_tasks": frozenset(),
        "create_task": frozenset(),
        "complete_task": frozenset({"task_exists:task_id"}),
        "add_note": frozenset(),
    },
    "email": {
        "list_inbox": frozenset(),
        "get_email": frozenset({"email_exists:email_id"}),
        "send_email": frozenset(),
        "create_draft": frozenset(),
        "reply_email": frozenset({"email_exists:email_id"}),
        "forward_email": frozenset({"email_exists:email_id"}),
        "get_thread": frozenset({"thread_exists:thread_id"}),
        "search_emails": frozenset(),
        "mark_read": frozenset({"email_exists:email_id"}),
        "mark_unread": frozenset({"email_exists:email_id"}),
        "archive_email": frozenset({"email_exists:email_id"}),
        "add_label": frozenset({"email_exists:email_id"}),
        "remove_label": frozenset({"email_exists:email_id"}),
        "get_attachments": frozenset({"email_exists:email_id"}),
        "move_to_thread": frozenset({"email_exists:email_id"}),
        "create_filter": frozenset(),
        "list_filters": frozenset(),
    },
    "food_delivery": {
        "search_restaurants": frozenset(),
        "list_restaurants": frozenset(),
        "get_restaurant": frozenset({"restaurant_exists:restaurant_id"}),
        "get_menu": frozenset({"restaurant_exists:restaurant_id"}),
        "get_popular_items": frozenset({"restaurant_exists:restaurant_id"}),
        "create_order": frozenset({"restaurant_exists:restaurant_id"}),
        "get_order": frozenset({"order_exists:order_id"}),
        "list_orders": frozenset(),
        "update_order_status": frozenset({"order_exists:order_id"}),
        "cancel_order": frozenset({"order_exists:order_id"}),
        "get_estimated_time": frozenset({"order_exists:order_id"}),
        "track_rider": frozenset({"order_exists:order_id"}),
        "rate_order": frozenset({"order_exists:order_id"}),
        "add_tip": frozenset({"order_exists:order_id"}),
        "reorder": frozenset({"order_exists:order_id"}),
        "contact_support": frozenset({"order_exists:order_id"}),
        "filter_by_dietary": frozenset(),
    },
    "issue_tracker": {
        "list_issues": frozenset(),
        "get_issue": frozenset({"issue_exists:issue_id"}),
        "create_issue": frozenset(),
        "update_issue": frozenset({"issue_exists:issue_id"}),
        "list_subtasks": frozenset(),
        "create_subtask": frozenset({"issue_exists:issue_id"}),
        "list_sprints": frozenset(),
        "create_sprint": frozenset(),
        "add_to_sprint": frozenset({"issue_exists:issue_id", "sprint_exists:sprint_id"}),
        "remove_from_sprint": frozenset({"issue_exists:issue_id", "sprint_exists:sprint_id"}),
        "assign_issue": frozenset({"issue_exists:issue_id"}),
        "comment_issue": frozenset({"issue_exists:issue_id"}),
        "add_label": frozenset({"issue_exists:issue_id"}),
        "remove_label": frozenset({"issue_exists:issue_id"}),
        "add_watcher": frozenset({"issue_exists:issue_id"}),
        "remove_watcher": frozenset({"issue_exists:issue_id"}),
        "transition_issue": frozenset({"issue_exists:issue_id"}),
        "set_milestone": frozenset({"issue_exists:issue_id"}),
        "time_track": frozenset({"issue_exists:issue_id"}),
        "get_time_report": frozenset(),
        "list_members": frozenset(),
    },
    "payments": {
        "list_invoices": frozenset(),
        "get_invoice": frozenset({"invoice_exists:invoice_id"}),
        "create_invoice": frozenset(),
        "pay_invoice": frozenset({"invoice_exists:invoice_id"}),
        "cancel_payment": frozenset({"payment_exists:payment_id"}),
        "refund_invoice": frozenset({"invoice_exists:invoice_id"}),
        "dispute_invoice": frozenset({"invoice_exists:invoice_id"}),
        "list_webhooks": frozenset(),
        "create_webhook": frozenset(),
        "delete_webhook": frozenset({"webhook_exists:webhook_id"}),
    },
    "team_chat": {
        "list_channels": frozenset(),
        "get_channel": frozenset({"channel_exists:channel_id"}),
        "create_channel": frozenset(),
        "archive_channel": frozenset({"channel_exists:channel_id"}),
        "send_message": frozenset({"channel_exists:channel_id"}),
        "send_dm": frozenset(),
        "get_thread": frozenset({"thread_exists:thread_id"}),
        "create_thread": frozenset({"channel_exists:channel_id"}),
        "search_messages": frozenset(),
        "react_message": frozenset({"message_exists:message_id"}),
        "get_user_status": frozenset(),
    },
    # Filesystem uses canonical typed-state contracts derived from tool
    # annotations (mutating/readonly) and parameter types (path→file entity).
    # These fallback entries document the state model; the canonical path in
    # _canonical_contracts() is the primary authority for implicit edges.
    "filesystem": {
        "ls": frozenset(),
        "cd": frozenset({"path_exists:path"}),
        "pwd": frozenset(),
        "cat": frozenset({"path_exists:path"}),
        "head": frozenset({"path_exists:path"}),
        "tail": frozenset({"path_exists:path"}),
        "wc": frozenset({"path_exists:path"}),
        "stat": frozenset({"path_exists:path"}),
        "find": frozenset(),
        "grep": frozenset({"path_exists:path"}),
        "tree": frozenset(),
        "mkdir": frozenset(),
        "touch": frozenset(),
        "mv": frozenset({"path_exists:source", "path_not_exists:target"}),
        "cp": frozenset({"path_exists:source", "path_not_exists:target"}),
        "rm": frozenset({"path_exists:path"}),
        "chmod": frozenset({"path_exists:path"}),
        "chown": frozenset({"path_exists:path"}),
        "umask": frozenset(),
        "du": frozenset(),
        "df": frozenset(),
        "symlink": frozenset(),
        "readlink": frozenset({"path_exists:path"}),
        "tar_create": frozenset(),
        "tar_extract": frozenset({"archive_exists:archive"}),
        "zip": frozenset(),
        "unzip": frozenset({"archive_exists:archive"}),
        "diff": frozenset({"path_exists:file1", "path_exists:file2"}),
        "sort": frozenset({"path_exists:path"}),
        "uniq": frozenset({"path_exists:path"}),
        "cut": frozenset({"path_exists:path"}),
        "sed": frozenset({"path_exists:path"}),
        "awk": frozenset({"path_exists:path"}),
        "md5sum": frozenset({"path_exists:path"}),
        "sha256sum": frozenset({"path_exists:path"}),
        "file_info": frozenset({"path_exists:path"}),
        "xxd": frozenset({"path_exists:path"}),
        "truncate": frozenset({"path_exists:path"}),
        "split": frozenset({"path_exists:path"}),
        "join": frozenset({"path_exists:file1", "path_exists:file2"}),
    },
}

_DEPENDENCY_TOOL_STATE_POSTCONDITIONS: dict[
    str, dict[str, frozenset[str]]
] = {
    "calendar": {
        "list_events": frozenset(),
        "search_events": frozenset(),
        "get_event": frozenset(),
        "create_event": frozenset({
            "event_exists:event_id", "event_nonrecurring:event_id",
        }),
        "update_event": frozenset(),
        "delete_event": frozenset({"event_absent:event_id"}),
        "create_recurring": frozenset({
            "event_exists:event_id", "event_recurring:event_id",
        }),
        "add_attendee": frozenset({"attendee_member:email"}),
        "remove_attendee": frozenset({"attendee_absent:email"}),
        "get_free_busy": frozenset(),
        "check_conflicts": frozenset(),
        "set_reminder": frozenset({"reminder_exists:event_id"}),
        "get_working_hours": frozenset(),
        "change_timezone": frozenset(),
        "respond_to_event": frozenset(),
        "export_calendar": frozenset(),
        "get_recurring_info": frozenset(),
    },
    "shopping": {
        "search_products": frozenset(),
        "get_product": frozenset(),
        "list_categories": frozenset(),
        "compare_products": frozenset(),
        "get_recommendations": frozenset(),
        "add_to_cart": frozenset({
            "cart_nonempty", "cart_member:product_id",
        }),
        # The cart membership/non-empty facts already held before update, and
        # setting the same quantity is a successful no-op. No predicate is
        # unconditionally newly established.
        "update_cart_quantity": frozenset(),
        "remove_from_cart": frozenset({"cart_absent:product_id"}),
        "get_cart": frozenset(),
        "clear_cart": frozenset({"cart_empty"}),
        "apply_coupon": frozenset({"coupon_applied"}),
        "get_coupons": frozenset(),
        "checkout": frozenset({
            "cart_empty", "order_exists:order_id", "order_status:placed",
        }),
        "get_order": frozenset(),
        "list_orders": frozenset(),
        "cancel_order": frozenset(),
        "return_order": frozenset({
            "order_status:returning",
            "return_exists:return_id",
        }),
        "get_return_status": frozenset(),
        "add_review": frozenset({
            "review_exists:review_id",
            "review_already_authored:product_id",
        }),
        "get_reviews": frozenset(),
        "add_to_wishlist": frozenset({"wishlist_member:product_id"}),
        "remove_from_wishlist": frozenset({"wishlist_absent:product_id"}),
        "get_wishlist": frozenset(),
    },
    "banking": {
        "list_accounts": frozenset(),
        "get_account_info": frozenset(),
        "get_balance": frozenset(),
        "get_history": frozenset(),
        "get_statement": frozenset(),
        "transfer": frozenset(),
        "wire_transfer": frozenset(),
        "deposit": frozenset(),
        "withdraw": frozenset(),
        "bill_pay": frozenset(),
        "schedule_transfer": frozenset({"scheduled_transfer_exists:scheduled_txn_id"}),
        "list_scheduled_transfers": frozenset(),
        "cancel_transfer": frozenset({"scheduled_transfer_absent:scheduled_txn_id"}),
        "freeze_account": frozenset({"account_frozen:account_id"}),
        "unfreeze_account": frozenset({"account_not_frozen:account_id"}),
        "verify_account": frozenset(),
        "get_exchange_rate": frozenset(),
        "apply_loan": frozenset({"loan_exists:account_id"}),
    },
    "crm": {
        "create_contact": frozenset({"contact_exists:contact_id"}),
        "list_contacts": frozenset(),
        "update_contact": frozenset(),
        "delete_contact": frozenset({"contact_absent:contact_id"}),
        "list_leads": frozenset(),
        "create_lead": frozenset({"lead_exists:lead_id"}),
        "update_lead": frozenset(),
        "delete_lead": frozenset({"lead_absent:lead_id"}),
        "convert_lead": frozenset({"deal_exists:deal_id", "lead_absent:lead_id"}),
        "list_deals": frozenset(),
        "get_deal": frozenset(),
        "create_deal": frozenset({"deal_exists:deal_id"}),
        "update_deal": frozenset(),
        "list_tasks": frozenset(),
        "create_task": frozenset({"task_exists:task_id"}),
        "complete_task": frozenset({"task_absent:task_id"}),
        "add_note": frozenset({"note_exists:note_id"}),
    },
    "email": {
        "list_inbox": frozenset(),
        "get_email": frozenset(),
        "send_email": frozenset({"email_exists:email_id", "thread_exists:thread_id"}),
        "create_draft": frozenset({"email_exists:email_id"}),
        "reply_email": frozenset({"email_exists:email_id"}),
        "forward_email": frozenset({"email_exists:email_id"}),
        "get_thread": frozenset(),
        "search_emails": frozenset(),
        "mark_read": frozenset(),
        "mark_unread": frozenset(),
        "archive_email": frozenset({"email_absent:email_id"}),
        "add_label": frozenset(),
        "remove_label": frozenset(),
        "get_attachments": frozenset(),
        "move_to_thread": frozenset(),
        "create_filter": frozenset({"filter_exists:filter_id"}),
        "list_filters": frozenset(),
    },
    "food_delivery": {
        "search_restaurants": frozenset(),
        "list_restaurants": frozenset(),
        "get_restaurant": frozenset(),
        "get_menu": frozenset(),
        "get_popular_items": frozenset(),
        "create_order": frozenset({"order_exists:order_id"}),
        "get_order": frozenset(),
        "list_orders": frozenset(),
        "update_order_status": frozenset(),
        "cancel_order": frozenset({"order_absent:order_id"}),
        "get_estimated_time": frozenset(),
        "track_rider": frozenset(),
        "rate_order": frozenset(),
        "add_tip": frozenset(),
        "reorder": frozenset({"order_exists:order_id"}),
        "contact_support": frozenset(),
        "filter_by_dietary": frozenset(),
    },
    "issue_tracker": {
        "list_issues": frozenset(),
        "get_issue": frozenset(),
        "create_issue": frozenset({"issue_exists:issue_id"}),
        "update_issue": frozenset(),
        "list_subtasks": frozenset(),
        "create_subtask": frozenset({"subtask_exists:subtask_id"}),
        "list_sprints": frozenset(),
        "create_sprint": frozenset({"sprint_exists:sprint_id"}),
        "add_to_sprint": frozenset({"issue_in_sprint:issue_id"}),
        "remove_from_sprint": frozenset({"issue_not_in_sprint:issue_id"}),
        "assign_issue": frozenset(),
        "comment_issue": frozenset({"comment_exists:comment_id"}),
        "add_label": frozenset(),
        "remove_label": frozenset(),
        "add_watcher": frozenset({"watcher_added:issue_id"}),
        "remove_watcher": frozenset({"watcher_removed:issue_id"}),
        "transition_issue": frozenset(),
        "set_milestone": frozenset(),
        "time_track": frozenset({"time_entry_exists:entry_id"}),
        "get_time_report": frozenset(),
        "list_members": frozenset(),
    },
    "payments": {
        "list_invoices": frozenset(),
        "get_invoice": frozenset(),
        "create_invoice": frozenset({"invoice_exists:invoice_id"}),
        "pay_invoice": frozenset({"payment_exists:payment_id"}),
        "cancel_payment": frozenset({"payment_absent:payment_id"}),
        "refund_invoice": frozenset({"refund_exists:refund_id"}),
        "dispute_invoice": frozenset({"dispute_exists:invoice_id"}),
        "list_webhooks": frozenset(),
        "create_webhook": frozenset({"webhook_exists:webhook_id"}),
        "delete_webhook": frozenset({"webhook_absent:webhook_id"}),
    },
    "team_chat": {
        "list_channels": frozenset(),
        "get_channel": frozenset(),
        "create_channel": frozenset({"channel_exists:channel_id"}),
        "archive_channel": frozenset({"channel_absent:channel_id"}),
        "send_message": frozenset({"message_exists:message_id"}),
        "send_dm": frozenset({"dm_exists:dm_id"}),
        "get_thread": frozenset(),
        "create_thread": frozenset({"thread_exists:thread_id"}),
        "search_messages": frozenset(),
        "react_message": frozenset(),
        "get_user_status": frozenset(),
    },
    # Filesystem postconditions mirror the canonical typed-state contracts.
    # Mutating tools establish path_exists; tools that create archives or
    # symlinks additionally set type/archive predicates.  See the comment in
    # _DEPENDENCY_TOOL_STATE_PRECONDITIONS above.
    "filesystem": {
        "ls": frozenset(),
        "cd": frozenset(),
        "pwd": frozenset(),
        "cat": frozenset(),
        "head": frozenset(),
        "tail": frozenset(),
        "wc": frozenset(),
        "stat": frozenset(),
        "find": frozenset(),
        "grep": frozenset(),
        "tree": frozenset(),
        "mkdir": frozenset({"path_exists:path"}),
        "touch": frozenset({"path_exists:path"}),
        "mv": frozenset({"path_absent:source", "path_exists:target"}),
        "cp": frozenset({"path_exists:target"}),
        "rm": frozenset({"path_absent:path"}),
        "chmod": frozenset(),
        "chown": frozenset(),
        "umask": frozenset(),
        "du": frozenset(),
        "df": frozenset(),
        "symlink": frozenset({"path_exists:link_path"}),
        "readlink": frozenset(),
        "tar_create": frozenset({"path_exists:archive"}),
        "tar_extract": frozenset(),
        "zip": frozenset({"path_exists:archive"}),
        "unzip": frozenset(),
        "diff": frozenset(),
        "sort": frozenset(),
        "uniq": frozenset(),
        "cut": frozenset(),
        "sed": frozenset(),
        "awk": frozenset(),
        "md5sum": frozenset(),
        "sha256sum": frozenset(),
        "file_info": frozenset(),
        "xxd": frozenset(),
        "truncate": frozenset(),
        "split": frozenset(),
        "join": frozenset(),
    },
}


_DEPENDENCY_OUTPUT_MIN_CARDINALITY: dict[tuple[str, str, str], int] = {
    # compare_products consumes an array with minItems=2.  The source
    # observation exposes repeated scalar product_id values.
    ("shopping", "compare_products", "product_id"): 2,
}
